### ISSUE TITLE
Git clone link in usage directions don't work

### ISSUE THREAD

**Issue by anaveragehuman** [CytoDev/conkyconf#1]
The clone link in your instructions doesn't seem to work, the correct one (found at the top of your repository) seems to be: https://github.com/CytoDev/conkyconf.git

**Comment by cytodev** [comment]
@AnAverageHuman, you probably don't have SSH set up since `git@github.com:CytoDev/conkyconf.git` is the SSH clone link. HTTPS works fine though, so I will edit the instructions to clone either via SSH or HTTPS.  

Thanks for bringing it to my attention!
